// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GodSpeak.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GodSpeak.Resources.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GetStartedText {
            get {
                return ResourceManager.GetString("GetStartedText", resourceCulture);
            }
        }
        
        public static string ClaimInviteCodeText {
            get {
                return ResourceManager.GetString("ClaimInviteCodeText", resourceCulture);
            }
        }
        
        public static string RequestInviteCodeText {
            get {
                return ResourceManager.GetString("RequestInviteCodeText", resourceCulture);
            }
        }
        
        public static string OkPopup {
            get {
                return ResourceManager.GetString("OkPopup", resourceCulture);
            }
        }
        
        public static string ErrorPopupTitle {
            get {
                return ResourceManager.GetString("ErrorPopupTitle", resourceCulture);
            }
        }
        
        public static string SuccessPopupTitle {
            get {
                return ResourceManager.GetString("SuccessPopupTitle", resourceCulture);
            }
        }
        
        public static string ErrorPopupText {
            get {
                return ResourceManager.GetString("ErrorPopupText", resourceCulture);
            }
        }
        
        public static string GetACode {
            get {
                return ResourceManager.GetString("GetACode", resourceCulture);
            }
        }
        
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        public static string InviteCodeRequiredMessage {
            get {
                return ResourceManager.GetString("InviteCodeRequiredMessage", resourceCulture);
            }
        }
        
        public static string InviteCodePlaceholder {
            get {
                return ResourceManager.GetString("InviteCodePlaceholder", resourceCulture);
            }
        }
        
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordConfirmPlaceholder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceholder", resourceCulture);
            }
        }
        
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        public static string ZipCodePlaceholder {
            get {
                return ResourceManager.GetString("ZipCodePlaceholder", resourceCulture);
            }
        }
        
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        public static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        public static string FirstNameRequiredMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string LastNameRequiredMessage {
            get {
                return ResourceManager.GetString("LastNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string CityRequiredMessage {
            get {
                return ResourceManager.GetString("CityRequiredMessage", resourceCulture);
            }
        }
        
        public static string StateRequiredMessage {
            get {
                return ResourceManager.GetString("StateRequiredMessage", resourceCulture);
            }
        }
        
        public static string RequestInviteSuccessfully {
            get {
                return ResourceManager.GetString("RequestInviteSuccessfully", resourceCulture);
            }
        }
        
        public static string ForgotPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessfully", resourceCulture);
            }
        }
        
        public static string PictureSourceQuestion {
            get {
                return ResourceManager.GetString("PictureSourceQuestion", resourceCulture);
            }
        }
        
        public static string PictureSourceFromGallery {
            get {
                return ResourceManager.GetString("PictureSourceFromGallery", resourceCulture);
            }
        }
        
        public static string PictureSourceFromCamera {
            get {
                return ResourceManager.GetString("PictureSourceFromCamera", resourceCulture);
            }
        }
        
        public static string PurchaseButtonText {
            get {
                return ResourceManager.GetString("PurchaseButtonText", resourceCulture);
            }
        }
        
        public static string PurchaseMoreInvitesButtonText {
            get {
                return ResourceManager.GetString("PurchaseMoreInvitesButtonText", resourceCulture);
            }
        }
        
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        public static string InAppPurchaseTitle {
            get {
                return ResourceManager.GetString("InAppPurchaseTitle", resourceCulture);
            }
        }
        
        public static string InAppPurchaseText {
            get {
                return ResourceManager.GetString("InAppPurchaseText", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string PurchaseSuccessTitle {
            get {
                return ResourceManager.GetString("PurchaseSuccessTitle", resourceCulture);
            }
        }
        
        public static string PurchaseSuccessText {
            get {
                return ResourceManager.GetString("PurchaseSuccessText", resourceCulture);
            }
        }
        
        public static string PurchasePageTitle {
            get {
                return ResourceManager.GetString("PurchasePageTitle", resourceCulture);
            }
        }
        
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        public static string InvitePageTitle {
            get {
                return ResourceManager.GetString("InvitePageTitle", resourceCulture);
            }
        }
        
        public static string MessageCategoriesPageTitle {
            get {
                return ResourceManager.GetString("MessageCategoriesPageTitle", resourceCulture);
            }
        }
        
        public static string MessageDaysTimesPageTitle {
            get {
                return ResourceManager.GetString("MessageDaysTimesPageTitle", resourceCulture);
            }
        }
        
        public static string ImpactPageTitle {
            get {
                return ResourceManager.GetString("ImpactPageTitle", resourceCulture);
            }
        }
        
        public static string SavedCategoriesSuccessful {
            get {
                return ResourceManager.GetString("SavedCategoriesSuccessful", resourceCulture);
            }
        }
        
        public static string SavedSettingsSuccessful {
            get {
                return ResourceManager.GetString("SavedSettingsSuccessful", resourceCulture);
            }
        }
        
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        public static string RegisterPageLoginInfo {
            get {
                return ResourceManager.GetString("RegisterPageLoginInfo", resourceCulture);
            }
        }
        
        public static string RegisterPagePasswordInfo {
            get {
                return ResourceManager.GetString("RegisterPagePasswordInfo", resourceCulture);
            }
        }
    }
}
