//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodSpeak.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GodSpeak.Resources.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GetStartedText {
            get {
                return ResourceManager.GetString("GetStartedText", resourceCulture);
            }
        }
        
        public static string ClaimInviteCodeText {
            get {
                return ResourceManager.GetString("ClaimInviteCodeText", resourceCulture);
            }
        }
        
        public static string RequestInviteCodeText {
            get {
                return ResourceManager.GetString("RequestInviteCodeText", resourceCulture);
            }
        }
        
        public static string OkPopup {
            get {
                return ResourceManager.GetString("OkPopup", resourceCulture);
            }
        }
        
        public static string ErrorPopupTitle {
            get {
                return ResourceManager.GetString("ErrorPopupTitle", resourceCulture);
            }
        }
        
        public static string SuccessPopupTitle {
            get {
                return ResourceManager.GetString("SuccessPopupTitle", resourceCulture);
            }
        }
        
        public static string ErrorPopupText {
            get {
                return ResourceManager.GetString("ErrorPopupText", resourceCulture);
            }
        }
        
        public static string GetACode {
            get {
                return ResourceManager.GetString("GetACode", resourceCulture);
            }
        }
        
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        public static string InviteCodeRequiredMessage {
            get {
                return ResourceManager.GetString("InviteCodeRequiredMessage", resourceCulture);
            }
        }
        
        public static string InviteCodePlaceholder {
            get {
                return ResourceManager.GetString("InviteCodePlaceholder", resourceCulture);
            }
        }
        
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string CurrentPasswordPlaceholder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordConfirmPlaceholder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceholder", resourceCulture);
            }
        }
        
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        public static string ZipCodePlaceholder {
            get {
                return ResourceManager.GetString("ZipCodePlaceholder", resourceCulture);
            }
        }
        
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        public static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        public static string FirstNameRequiredMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string LastNameRequiredMessage {
            get {
                return ResourceManager.GetString("LastNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string CityRequiredMessage {
            get {
                return ResourceManager.GetString("CityRequiredMessage", resourceCulture);
            }
        }
        
        public static string StateRequiredMessage {
            get {
                return ResourceManager.GetString("StateRequiredMessage", resourceCulture);
            }
        }
        
        public static string RequestInviteSuccessfully {
            get {
                return ResourceManager.GetString("RequestInviteSuccessfully", resourceCulture);
            }
        }
        
        public static string ForgotPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessfully", resourceCulture);
            }
        }
        
        public static string PictureSourceQuestion {
            get {
                return ResourceManager.GetString("PictureSourceQuestion", resourceCulture);
            }
        }
        
        public static string PictureSourceFromGallery {
            get {
                return ResourceManager.GetString("PictureSourceFromGallery", resourceCulture);
            }
        }
        
        public static string PictureSourceFromCamera {
            get {
                return ResourceManager.GetString("PictureSourceFromCamera", resourceCulture);
            }
        }
        
        public static string PurchaseButtonText {
            get {
                return ResourceManager.GetString("PurchaseButtonText", resourceCulture);
            }
        }
        
        public static string PurchaseMoreInvitesButtonText {
            get {
                return ResourceManager.GetString("PurchaseMoreInvitesButtonText", resourceCulture);
            }
        }
        
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        public static string InAppPurchaseTitle {
            get {
                return ResourceManager.GetString("InAppPurchaseTitle", resourceCulture);
            }
        }
        
        public static string InAppPurchaseText {
            get {
                return ResourceManager.GetString("InAppPurchaseText", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string PurchaseSuccessTitle {
            get {
                return ResourceManager.GetString("PurchaseSuccessTitle", resourceCulture);
            }
        }
        
        public static string PurchaseSuccessText {
            get {
                return ResourceManager.GetString("PurchaseSuccessText", resourceCulture);
            }
        }
        
        public static string PurchasePageTitle {
            get {
                return ResourceManager.GetString("PurchasePageTitle", resourceCulture);
            }
        }
        
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        public static string InvitePageTitle {
            get {
                return ResourceManager.GetString("InvitePageTitle", resourceCulture);
            }
        }
        
        public static string MessageCategoriesPageTitle {
            get {
                return ResourceManager.GetString("MessageCategoriesPageTitle", resourceCulture);
            }
        }
        
        public static string MessageDaysTimesPageTitle {
            get {
                return ResourceManager.GetString("MessageDaysTimesPageTitle", resourceCulture);
            }
        }
        
        public static string ImpactPageTitle {
            get {
                return ResourceManager.GetString("ImpactPageTitle", resourceCulture);
            }
        }
        
        public static string SavedCategoriesSuccessful {
            get {
                return ResourceManager.GetString("SavedCategoriesSuccessful", resourceCulture);
            }
        }
        
        public static string SavedSettingsSuccessful {
            get {
                return ResourceManager.GetString("SavedSettingsSuccessful", resourceCulture);
            }
        }
        
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        public static string RegisterPageLoginInfo {
            get {
                return ResourceManager.GetString("RegisterPageLoginInfo", resourceCulture);
            }
        }
        
        public static string RegisterPagePasswordInfo {
            get {
                return ResourceManager.GetString("RegisterPagePasswordInfo", resourceCulture);
            }
        }
        
        public static string TermsCondititionText {
            get {
                return ResourceManager.GetString("TermsCondititionText", resourceCulture);
            }
        }
        
        public static string MessageSettingsPageTitle {
            get {
                return ResourceManager.GetString("MessageSettingsPageTitle", resourceCulture);
            }
        }
        
        public static string GetStartedCitation {
            get {
                return ResourceManager.GetString("GetStartedCitation", resourceCulture);
            }
        }
        
        public static string GetStartedAuthor {
            get {
                return ResourceManager.GetString("GetStartedAuthor", resourceCulture);
            }
        }
        
        public static string GetStartedSubmitInviteCode {
            get {
                return ResourceManager.GetString("GetStartedSubmitInviteCode", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string SuccessGiftCodeTitle {
            get {
                return ResourceManager.GetString("SuccessGiftCodeTitle", resourceCulture);
            }
        }
        
        public static string SuccessGiftCodeText {
            get {
                return ResourceManager.GetString("SuccessGiftCodeText", resourceCulture);
            }
        }
        
        public static string AnonymousTitle {
            get {
                return ResourceManager.GetString("AnonymousTitle", resourceCulture);
            }
        }
        
        public static string AnonymousText {
            get {
                return ResourceManager.GetString("AnonymousText", resourceCulture);
            }
        }
        
        public static string AnonymousSubmit {
            get {
                return ResourceManager.GetString("AnonymousSubmit", resourceCulture);
            }
        }
        
        public static string AnonymousNevermind {
            get {
                return ResourceManager.GetString("AnonymousNevermind", resourceCulture);
            }
        }
        
        public static string AnonymousInputPlaceholder {
            get {
                return ResourceManager.GetString("AnonymousInputPlaceholder", resourceCulture);
            }
        }
        
        public static string AnonymousSuccessTitle {
            get {
                return ResourceManager.GetString("AnonymousSuccessTitle", resourceCulture);
            }
        }
        
        public static string AnonymousSuccessText {
            get {
                return ResourceManager.GetString("AnonymousSuccessText", resourceCulture);
            }
        }
        
        public static string AnonymousSuccessButtonTitle {
            get {
                return ResourceManager.GetString("AnonymousSuccessButtonTitle", resourceCulture);
            }
        }
        
        public static string SuccessfulRegisterPopupTitle {
            get {
                return ResourceManager.GetString("SuccessfulRegisterPopupTitle", resourceCulture);
            }
        }
        
        public static string SuccessfulRegisterPopupText {
            get {
                return ResourceManager.GetString("SuccessfulRegisterPopupText", resourceCulture);
            }
        }
        
        public static string SuccessfulRegisterButtonText {
            get {
                return ResourceManager.GetString("SuccessfulRegisterButtonText", resourceCulture);
            }
        }
        
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        public static string BadRequestTitle {
            get {
                return ResourceManager.GetString("BadRequestTitle", resourceCulture);
            }
        }
        
        public static string LoginInvalidEmailPassword {
            get {
                return ResourceManager.GetString("LoginInvalidEmailPassword", resourceCulture);
            }
        }
        
        public static string ForgotMyPasswordButtonTitle {
            get {
                return ResourceManager.GetString("ForgotMyPasswordButtonTitle", resourceCulture);
            }
        }
        
        public static string ForgotMyPasswordLinkText {
            get {
                return ResourceManager.GetString("ForgotMyPasswordLinkText", resourceCulture);
            }
        }
        
        public static string NeedToRegister {
            get {
                return ResourceManager.GetString("NeedToRegister", resourceCulture);
            }
        }
        
        public static string RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordTitle", resourceCulture);
            }
        }
        
        public static string RecoverPasswordText {
            get {
                return ResourceManager.GetString("RecoverPasswordText", resourceCulture);
            }
        }
        
        public static string SendInstructions {
            get {
                return ResourceManager.GetString("SendInstructions", resourceCulture);
            }
        }
        
        public static string RecoverPasswordSuccessText {
            get {
                return ResourceManager.GetString("RecoverPasswordSuccessText", resourceCulture);
            }
        }
        
        public static string NumberOfMessagesText {
            get {
                return ResourceManager.GetString("NumberOfMessagesText", resourceCulture);
            }
        }
        
        public static string MenuCitationText {
            get {
                return ResourceManager.GetString("MenuCitationText", resourceCulture);
            }
        }
        
        public static string MenuCitationAuthor {
            get {
                return ResourceManager.GetString("MenuCitationAuthor", resourceCulture);
            }
        }
        
        public static string MenuMessageSettings {
            get {
                return ResourceManager.GetString("MenuMessageSettings", resourceCulture);
            }
        }
        
        public static string MyProfileSettings {
            get {
                return ResourceManager.GetString("MyProfileSettings", resourceCulture);
            }
        }
        
        public static string LogoutSettings {
            get {
                return ResourceManager.GetString("LogoutSettings", resourceCulture);
            }
        }
        
        public static string SubmitBugFeedback {
            get {
                return ResourceManager.GetString("SubmitBugFeedback", resourceCulture);
            }
        }
        
        public static string MyProfilePageTitle {
            get {
                return ResourceManager.GetString("MyProfilePageTitle", resourceCulture);
            }
        }
        
        public static string MyProfileUpdateInfo {
            get {
                return ResourceManager.GetString("MyProfileUpdateInfo", resourceCulture);
            }
        }
        
        public static string MyProfileChangePassword {
            get {
                return ResourceManager.GetString("MyProfileChangePassword", resourceCulture);
            }
        }
        
        public static string MyProfileSuccessTitle {
            get {
                return ResourceManager.GetString("MyProfileSuccessTitle", resourceCulture);
            }
        }
        
        public static string MyProfileSuccessText {
            get {
                return ResourceManager.GetString("MyProfileSuccessText", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string ScripturesDelivered {
            get {
                return ResourceManager.GetString("ScripturesDelivered", resourceCulture);
            }
        }
        
        public static string GiftsClaimed {
            get {
                return ResourceManager.GetString("GiftsClaimed", resourceCulture);
            }
        }
        
        public static string ShareDescription {
            get {
                return ResourceManager.GetString("ShareDescription", resourceCulture);
            }
        }
        
        public static string ShareWithFriend {
            get {
                return ResourceManager.GetString("ShareWithFriend", resourceCulture);
            }
        }
        
        public static string ShareWithWorld {
            get {
                return ResourceManager.GetString("ShareWithWorld", resourceCulture);
            }
        }
        
        public static string GiftiOS {
            get {
                return ResourceManager.GetString("GiftiOS", resourceCulture);
            }
        }
        
        public static string ShareGiftsLeft {
            get {
                return ResourceManager.GetString("ShareGiftsLeft", resourceCulture);
            }
        }
        
        public static string DonateStranger {
            get {
                return ResourceManager.GetString("DonateStranger", resourceCulture);
            }
        }
        
        public static string DidYouKnow {
            get {
                return ResourceManager.GetString("DidYouKnow", resourceCulture);
            }
        }
        
        public static string DidYouKnowDeliveredGifts {
            get {
                return ResourceManager.GetString("DidYouKnowDeliveredGifts", resourceCulture);
            }
        }
        
        public static string DidYouKnowPurchasedGifts {
            get {
                return ResourceManager.GetString("DidYouKnowPurchasedGifts", resourceCulture);
            }
        }
        
        public static string DidYouKnowDonatedGifts {
            get {
                return ResourceManager.GetString("DidYouKnowDonatedGifts", resourceCulture);
            }
        }
        
        public static string InviteBundleDescription {
            get {
                return ResourceManager.GetString("InviteBundleDescription", resourceCulture);
            }
        }
        
        public static string SendGift {
            get {
                return ResourceManager.GetString("SendGift", resourceCulture);
            }
        }
        
        public static string SendInvitation {
            get {
                return ResourceManager.GetString("SendInvitation", resourceCulture);
            }
        }
        
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        public static string ShareWithFriendsTitle {
            get {
                return ResourceManager.GetString("ShareWithFriendsTitle", resourceCulture);
            }
        }
        
        public static string ShareWithFriendsDescription {
            get {
                return ResourceManager.GetString("ShareWithFriendsDescription", resourceCulture);
            }
        }
        
        public static string Individually {
            get {
                return ResourceManager.GetString("Individually", resourceCulture);
            }
        }
        
        public static string ViaEmail {
            get {
                return ResourceManager.GetString("ViaEmail", resourceCulture);
            }
        }
        
        public static string SortByClaimDate {
            get {
                return ResourceManager.GetString("SortByClaimDate", resourceCulture);
            }
        }
        
        public static string CongratulateThem {
            get {
                return ResourceManager.GetString("CongratulateThem", resourceCulture);
            }
        }
        
        public static string EncourageThem {
            get {
                return ResourceManager.GetString("EncourageThem", resourceCulture);
            }
        }
        
        public static string ClaimedDateDescription {
            get {
                return ResourceManager.GetString("ClaimedDateDescription", resourceCulture);
            }
        }
        
        public static string HasGiftedPeopleText {
            get {
                return ResourceManager.GetString("HasGiftedPeopleText", resourceCulture);
            }
        }
        
        public static string HasNotGiftedPeopleText {
            get {
                return ResourceManager.GetString("HasNotGiftedPeopleText", resourceCulture);
            }
        }
        
        public static string IDontHaveCodeLink {
            get {
                return ResourceManager.GetString("IDontHaveCodeLink", resourceCulture);
            }
        }
        
        public static string ImRegisteredLink {
            get {
                return ResourceManager.GetString("ImRegisteredLink", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyTerms {
            get {
                return ResourceManager.GetString("PrivacyPolicyTerms", resourceCulture);
            }
        }
        
        public static string SelectWhoToSendMailPageTitle {
            get {
                return ResourceManager.GetString("SelectWhoToSendMailPageTitle", resourceCulture);
            }
        }
        
        public static string ComposeEmail {
            get {
                return ResourceManager.GetString("ComposeEmail", resourceCulture);
            }
        }
        
        public static string EmailSearchPlaceholder {
            get {
                return ResourceManager.GetString("EmailSearchPlaceholder", resourceCulture);
            }
        }
        
        public static string ContactAccessDenied {
            get {
                return ResourceManager.GetString("ContactAccessDenied", resourceCulture);
            }
        }
        
        public static string ShareEmailSubject {
            get {
                return ResourceManager.GetString("ShareEmailSubject", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ShareEmailBody {
            get {
                return ResourceManager.GetString("ShareEmailBody", resourceCulture);
            }
        }
        
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        public static string RetrievingSettings {
            get {
                return ResourceManager.GetString("RetrievingSettings", resourceCulture);
            }
        }
        
        public static string SavingSettings {
            get {
                return ResourceManager.GetString("SavingSettings", resourceCulture);
            }
        }
        
        public static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        public static string SortByGiftsGiven {
            get {
                return ResourceManager.GetString("SortByGiftsGiven", resourceCulture);
            }
        }
        
        public static string RetrievingMessages {
            get {
                return ResourceManager.GetString("RetrievingMessages", resourceCulture);
            }
        }
        
        public static string MessageSettingsNotSelected {
            get {
                return ResourceManager.GetString("MessageSettingsNotSelected", resourceCulture);
            }
        }
        
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        public static string GiftToFriendText {
            get {
                return ResourceManager.GetString("GiftToFriendText", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string DonateInvite {
            get {
                return ResourceManager.GetString("DonateInvite", resourceCulture);
            }
        }
        
        public static string PurchaseInvitesText {
            get {
                return ResourceManager.GetString("PurchaseInvitesText", resourceCulture);
            }
        }
        
        public static string ShareWithNoBalance {
            get {
                return ResourceManager.GetString("ShareWithNoBalance", resourceCulture);
            }
        }
        
        public static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        public static string PayItForward {
            get {
                return ResourceManager.GetString("PayItForward", resourceCulture);
            }
        }
        
        public static string DontWantToPayItForward {
            get {
                return ResourceManager.GetString("DontWantToPayItForward", resourceCulture);
            }
        }
        
        public static string TapToPayItForward {
            get {
                return ResourceManager.GetString("TapToPayItForward", resourceCulture);
            }
        }
        
        public static string GodSpeakWebSite {
            get {
                return ResourceManager.GetString("GodSpeakWebSite", resourceCulture);
            }
        }
        
        public static string UnableToConnectToStore {
            get {
                return ResourceManager.GetString("UnableToConnectToStore", resourceCulture);
            }
        }
        
        public static string UnableToProcessOrder {
            get {
                return ResourceManager.GetString("UnableToProcessOrder", resourceCulture);
            }
        }
        
        public static string ProcessingOrder {
            get {
                return ResourceManager.GetString("ProcessingOrder", resourceCulture);
            }
        }
        
        public static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        public static string ImpactQuestion {
            get {
                return ResourceManager.GetString("ImpactQuestion", resourceCulture);
            }
        }
        
        public static string WhoReferrerPageTitle {
            get {
                return ResourceManager.GetString("WhoReferrerPageTitle", resourceCulture);
            }
        }
        
        public static string UseContactsButton {
            get {
                return ResourceManager.GetString("UseContactsButton", resourceCulture);
            }
        }
        
        public static string WhoReferredBoxTitle {
            get {
                return ResourceManager.GetString("WhoReferredBoxTitle", resourceCulture);
            }
        }
        
        public static string WhoReferredBoxTextContent {
            get {
                return ResourceManager.GetString("WhoReferredBoxTextContent", resourceCulture);
            }
        }
        
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        public static string InviteThem {
            get {
                return ResourceManager.GetString("InviteThem", resourceCulture);
            }
        }
        
        public static string ComposeMessateTitle {
            get {
                return ResourceManager.GetString("ComposeMessateTitle", resourceCulture);
            }
        }
        
        public static string FromAddressPlaceholder {
            get {
                return ResourceManager.GetString("FromAddressPlaceholder", resourceCulture);
            }
        }
        
        public static string SubjectPlaceholder {
            get {
                return ResourceManager.GetString("SubjectPlaceholder", resourceCulture);
            }
        }
        
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        public static string SendEmailSubject {
            get {
                return ResourceManager.GetString("SendEmailSubject", resourceCulture);
            }
        }
        
        public static string InviteSentSuccessfully {
            get {
                return ResourceManager.GetString("InviteSentSuccessfully", resourceCulture);
            }
        }
        
        public static string FromAddressRequired {
            get {
                return ResourceManager.GetString("FromAddressRequired", resourceCulture);
            }
        }
        
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }
        
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        public static string LearnHowToPayForward {
            get {
                return ResourceManager.GetString("LearnHowToPayForward", resourceCulture);
            }
        }
        
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        public static string GiftAndroid {
            get {
                return ResourceManager.GetString("GiftAndroid", resourceCulture);
            }
        }
        
        public static string ReferringEmailAddressPlaceholder {
            get {
                return ResourceManager.GetString("ReferringEmailAddressPlaceholder", resourceCulture);
            }
        }
        
        public static string ReferrerSectionTitle {
            get {
                return ResourceManager.GetString("ReferrerSectionTitle", resourceCulture);
            }
        }
        
        public static string ReferrerSectionDescription {
            get {
                return ResourceManager.GetString("ReferrerSectionDescription", resourceCulture);
            }
        }
        
        public static string GiftToIphoneUser {
            get {
                return ResourceManager.GetString("GiftToIphoneUser", resourceCulture);
            }
        }
        
        public static string GiftToAndroidUser {
            get {
                return ResourceManager.GetString("GiftToAndroidUser", resourceCulture);
            }
        }
        
        public static string GiftToChurch {
            get {
                return ResourceManager.GetString("GiftToChurch", resourceCulture);
            }
        }
        
        public static string FollowUpWithFriends {
            get {
                return ResourceManager.GetString("FollowUpWithFriends", resourceCulture);
            }
        }
        
        public static string TellFriendsAboutGodSpeak {
            get {
                return ResourceManager.GetString("TellFriendsAboutGodSpeak", resourceCulture);
            }
        }
        
        public static string OpenGodSpeakReminder {
            get {
                return ResourceManager.GetString("OpenGodSpeakReminder", resourceCulture);
            }
        }
        
        public static string DoNotKnowPlatform {
            get {
                return ResourceManager.GetString("DoNotKnowPlatform", resourceCulture);
            }
        }
        
        public static string ReachOutTitle {
            get {
                return ResourceManager.GetString("ReachOutTitle", resourceCulture);
            }
        }
        
        public static string ReachOutText {
            get {
                return ResourceManager.GetString("ReachOutText", resourceCulture);
            }
        }
        
        public static string ReachOutViaEmail {
            get {
                return ResourceManager.GetString("ReachOutViaEmail", resourceCulture);
            }
        }
        
        public static string ReachOutViaTextMessage {
            get {
                return ResourceManager.GetString("ReachOutViaTextMessage", resourceCulture);
            }
        }
        
        public static string ReachOutMessageBody {
            get {
                return ResourceManager.GetString("ReachOutMessageBody", resourceCulture);
            }
        }
        
        public static string ReachOutMessageSubject {
            get {
                return ResourceManager.GetString("ReachOutMessageSubject", resourceCulture);
            }
        }
    }
}
